export const aboutInformation = {
  resume: `aboutInfo.resume`,
  results: [
    "aboutInfo.results.0",
    "aboutInfo.results.1",
    "aboutInfo.results.2",
    "aboutInfo.results.3",
    "aboutInfo.results.4",
  ],
  skills: {
    softSkills: [
      "aboutInfo.skills.softSkills.0",
      "aboutInfo.skills.softSkills.1",
      "aboutInfo.skills.softSkills.2",
      "aboutInfo.skills.softSkills.3",
      "aboutInfo.skills.softSkills.4",
      "aboutInfo.skills.softSkills.5",
      "aboutInfo.skills.softSkills.6",
      "aboutInfo.skills.softSkills.7",
    ],
    hardSkills: [
      "aboutInfo.skills.hardSkills.0",
      "aboutInfo.skills.hardSkills.1",
      "aboutInfo.skills.hardSkills.2",
      "aboutInfo.skills.hardSkills.3",
      "aboutInfo.skills.hardSkills.4",
      "aboutInfo.skills.hardSkills.5",
      "aboutInfo.skills.hardSkills.6",
      "aboutInfo.skills.hardSkills.7",
      "aboutInfo.skills.hardSkills.8",
      "aboutInfo.skills.hardSkills.9",
      "aboutInfo.skills.hardSkills.10",
      "aboutInfo.skills.hardSkills.11",
      "aboutInfo.skills.hardSkills.12",
      "aboutInfo.skills.hardSkills.13",
      "aboutInfo.skills.hardSkills.14",
      "aboutInfo.skills.hardSkills.15"
    ],
  },
};
