export const experiences = [
  {
    role: "Gerente de projetos",
    company: "Tata Consultancy Services (Índia)",
    activitys: [
      "Gestão de mais de 10 projetos/contas em clientes LATAM e Estados Unidos.",
      "Gerenciamento de +100 associados entre projetos.",
      "Treinamento e mentoria para gestores de projetos.",
      "Realização de reuniões de vendas / pré-vendas e apresentação de decks.",
      "Elaboração de RFPs.",
      "Identificação de oportunidades de negócios dentro de clientes e stakeholders.",
      "Criação e implementação de KPIs e metas de projetos.",
      "Atuação direta no P&L dos projetos com ações de MIP.",
      "Elaboração de estratégias financeiras.",
      "Realização de análise de riscos.",
      "Reestruturação e padronização de equipes.",
      "Construção e alimentação de Pipeline.",
      "Participações em repactuações contratuais e elaboração de pleitos.",
      "Adequação e acompanhamento de auditorias internas.",
      "Reports para gestão executiva e diretoria.",
      "Monitoramento do cumprimento das cláusulas contratuais entre empresa x cliente.",
      "Participação em iniciativas tecnológicas com o cliente.",
      "Implementação de plano de melhoria de performance para associados.",
      "Elaboração de processos internos e distribuição de atividades.",
      "Realização de feedbacks 1 a 1 e feedbacks anuais.",
    ],
  },
  {
    role: "Consultor",
    company: "Prime IT (Portugal)",
    activitys: [
      "Direcionamentos na construção de fluxos de entrega na área de RPA.",
      "Direcionamentos na implementação de padrões de documentações na área de RPA.",
      "Levantamento de comparativos entre esforço humano x esforço de robôs.",
      "Participação em cerimônias de SCRUM.",
      "Elaboração de PDD, TDD, SDD, dentre outras documentações técnicas.",
      "Leitura e mapeamento de estruturas AS-IS e TO-BE.",
      "Análise/Especificação de requisitos e processos.",
      "Comunicação com clientes para atualizações, homologações e viabilidades de projetos.",
      "Análise de viabilidade de novas automações.",
      "Estimativa de tempo de execução de projetos em vigor.",
      "Automação de processos utilizando Automation Anywhere A360 e Control Room.",
      "Integrações com softwares, plataformas e websites.",
      "Análise, construção e padronização de arquiteturas de robôs e códigos.",
      "Realização de operações e testes dentro e fora de produção.",
      "Aplicação de conceitos BPM, DRY e SOLID.",
    ],
  },
  {
    role: "Tech Lead",
    company: "GAVB / Grupo Boticário (Brasil)",
    activitys: [
      "Automação de processos utilizando Automation Anywhere A360.",
      "Integrações com softwares, plataformas e websites.",
      "Análise, construção e padronização de arquiteturas de robôs e códigos.",
      "Realização de operações e testes dentro e fora de produção, com a presença de clientes quando necessário.",
      "Utilização da Control Room, IQBot, AARI e Bot Insights.",
      "Aplicação de conceitos BPM, DRY e SOLID.",
      "Desenvolvimentos de POCs.",
      "Construção de PDD, TDD, SDD, dentre outras documentações técnicas.",
      "Liderança de equipes em projetos.",
      "Análise de pontos fortes e de melhoria da equipe.",
      "Leitura e mapeamento de estruturas AS-IS e TO-BE.",
      "Análise/Especificação de requisitos e processos.",
      "Comunicação com clientes para atualizações, homologações e viabilidades de projetos.",
      "Avaliação de construção de códigos e adequação de boas práticas.",
      "Implementação de metodologia SCRUM na área de RPA.",
      "Análise de viabilidade de novas automações.",
      "Participação em reuniões de pré-venda técnica.",
      "Capacitação de desenvolvedores em RPA e SoftSkills.",
    ],
  },
  {
    role: "Desenvolvedor Fullstack",
    company: "Evonnis (Brasil)",
    activitys: [
      "Desenvolvimento de plataformas E-Commerce e Websites de Marca.",
      "Participação em configuração de servidores via AWS.",
      "Gestão e participação dos modelos de trabalho SCRUM, Metodologia Ágil e KANBAN.",
      "Utilização de linguagens PHP, CSS3, HTML5, MySQL e Javascript (padrão MVC).",
      "Atuação em projetos utilizando OpenCart, WooCommerce e Wordpress.",
      "Atuação básica na área de manutenção de servidores.",
      "Utilização de plataformas de gestão de projetos (Jira e Notion).",
      "Utilização de ambientes de desenvolvimento (VsCode, Sublime e Xampp).",
      "Atuação no suporte e resolução de bugs com clientes.",
      "Treinamento de colaboradores para funcionalidades do sistema.",
      "Comunicação com gestores para novos projetos.",
    ],
  },
  {
    role: "Supervisor Administrativo e Comercial",
    company: "Evonnis (Brasil)",
    activitys: [
      "Desenvolvimento de plataformas E-Commerce e Websites de Marca.",
      "Participação em configuração de servidores via AWS.",
      "Gestão e participação dos modelos de trabalho SCRUM, Metodologia Ágil e KANBAN.",
      "Utilização de linguagens PHP, CSS3, HTML5, MySQL e Javascript (padrão MVC).",
      "Atuação em projetos utilizando OpenCart, WooCommerce e Wordpress.",
      "Atuação básica na área de manutenção de servidores.",
      "Utilização de plataformas de gestão de projetos (Jira e Notion).",
      "Utilização de ambientes de desenvolvimento (VsCode, Sublime e Xampp).",
      "Atuação no suporte e resolução de bugs com clientes.",
      "Treinamento de colaboradores para funcionalidades do sistema.",
      "Comunicação com gestores para novos projetos.",
    ],
  },
];
