export const experiences = [
  {
    role: "experiences.roles.0",
    company: "experiences.enterprises.0",
    activitys: [
      "experiences.roleFunctions.0.0",
      "experiences.roleFunctions.0.1",
      "experiences.roleFunctions.0.2",
      "experiences.roleFunctions.0.3",
      "experiences.roleFunctions.0.4",
      "experiences.roleFunctions.0.5",
      "experiences.roleFunctions.0.6",
      "experiences.roleFunctions.0.7",
      "experiences.roleFunctions.0.8",
      "experiences.roleFunctions.0.9",
      "experiences.roleFunctions.0.10",
      "experiences.roleFunctions.0.11",
      "experiences.roleFunctions.0.12",
      "experiences.roleFunctions.0.13",
      "experiences.roleFunctions.0.14",
      "experiences.roleFunctions.0.15",
      "experiences.roleFunctions.0.16",
      "experiences.roleFunctions.0.17",
      "experiences.roleFunctions.0.18",
      "experiences.roleFunctions.0.19",
    ],
  },
  {
    role: "experiences.roles.1",
    company: "experiences.enterprises.1",
    activitys: [
      "experiences.roleFunctions.1.0",
      "experiences.roleFunctions.1.1",
      "experiences.roleFunctions.1.2",
      "experiences.roleFunctions.1.3",
      "experiences.roleFunctions.1.4",
      "experiences.roleFunctions.1.5",
      "experiences.roleFunctions.1.6",
      "experiences.roleFunctions.1.7",
      "experiences.roleFunctions.1.8",
      "experiences.roleFunctions.1.9",
      "experiences.roleFunctions.1.10",
      "experiences.roleFunctions.1.11",
      "experiences.roleFunctions.1.12",
      "experiences.roleFunctions.1.13",
      "experiences.roleFunctions.1.14",
    ],
  },
  {
    role: "experiences.roles.2",
    company: "experiences.enterprises.2",
    activitys: [
      "experiences.roleFunctions.2.0",
      "experiences.roleFunctions.2.1",
      "experiences.roleFunctions.2.2",
      "experiences.roleFunctions.2.3",
      "experiences.roleFunctions.2.4",
      "experiences.roleFunctions.2.5",
      "experiences.roleFunctions.2.6",
      "experiences.roleFunctions.2.7",
      "experiences.roleFunctions.2.8",
      "experiences.roleFunctions.2.9",
      "experiences.roleFunctions.2.10",
      "experiences.roleFunctions.2.11",
      "experiences.roleFunctions.2.12",
      "experiences.roleFunctions.2.13",
      "experiences.roleFunctions.2.14",
      "experiences.roleFunctions.2.15",
      "experiences.roleFunctions.2.16",
      "experiences.roleFunctions.2.17",
    ],
  },
  {
    role: "experiences.roles.3",
    company: "experiences.enterprises.3",
    activitys: [
      "experiences.roleFunctions.3.0",
      "experiences.roleFunctions.3.1",
      "experiences.roleFunctions.3.2",
      "experiences.roleFunctions.3.3",
      "experiences.roleFunctions.3.4",
      "experiences.roleFunctions.3.5",
      "experiences.roleFunctions.3.6",
      "experiences.roleFunctions.3.7",
      "experiences.roleFunctions.3.8",
      "experiences.roleFunctions.3.9",
      "experiences.roleFunctions.3.10",
    ],
  },
  {
    role: "experiences.roles.4",
    company: "experiences.enterprises.4",
    activitys: [
      "experiences.roleFunctions.4.0",
      "experiences.roleFunctions.4.1",
      "experiences.roleFunctions.4.2",
      "experiences.roleFunctions.4.3",
      "experiences.roleFunctions.4.4",
      "experiences.roleFunctions.4.5",
      "experiences.roleFunctions.4.6",
      "experiences.roleFunctions.4.7",
      "experiences.roleFunctions.4.8",
      "experiences.roleFunctions.4.9",
      "experiences.roleFunctions.4.10",
    ],
  },
];
